string NombreKiosco = "Kiosco Siempre";
Console.Write("Ingrese el nombre del cajero: ");
string NombreCajero = Console.ReadLine();
Console.WriteLine();
Console.WriteLine($"{NombreKiosco}");
Console.WriteLine($"Bienvenido, {NombreCajero}. Caja abierta");
Console.WriteLine();
Console.Write("Ingrese el nombre de un producto: ");
string NombreProducto = Console.ReadLine();
Console.Write("Ingrese el precio del producto: ");
decimal PrecioProducto = decimal.Parse(Console.ReadLine());
Console.WriteLine();
Console.WriteLine($"El producto {NombreProducto} tiene un precio de ${PrecioProducto}");
Console.WriteLine();
Console.ReadKey();